# Site settings
title: Good Clean Read
tag_text: Good Clean Read
description: A responsive template for publishing single-page websites, articles that are easy on the eyes
url: "http://sailbuddy.net"

sass:
  sass_dir: css
  style: compressed

# Build settings
markdown: kramdown

exclude:
- README.md
- sample.md
- Makefile
- LICENSE
- CNAME
